version: '3.3'

services:
  leantime_db:
    image: mysql:8.0
    container_name: mysql_leantime
    volumes:
      - $PWD/db/leantime.sql:/docker-entrypoint-initdb.d/init.sql
      - $PWD/mysqldb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - lean_network
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  leantime:
    image: twist250/leantime
    container_name: leantime
    restart: unless-stopped
    networks:
      - lean_network
    environment:
      LEAN_APP_URL: '${BASE_URL}'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      LEAN_SITENAME: '${SITE_NAME}'                                         # Name of your site, can be changed later
      LEAN_DB_HOST: 'mysql_leantime'                                    # Database host, derived from container_name in leantime_db container
      LEAN_DB_USER: '${DB_USER}'
      LEAN_DB_PASSWORD: '${DB_PASSWORD}'
      LEAN_DB_DATABASE: '${DB_NAME}'
      LEAN_DEFAULT_TIMEZONE: 'Africa/Kigali'                         # Set default server timezone
      LEAN_SESSION_PASSWORD: '${SESSION_PASS}'         # Salting sessions. Replace with a strong password
      LEAN_SESSION_EXPIRATION: '${SESSION_EXP}'                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours
    volumes:
      - $PWD/public_userfiles:/var/www/html/public/userfiles
      - $PWD/userfiles:/var/www/html/userfiles
    ports:
      - "8080:80"                                                       # The port to expose and access Leantime
    depends_on:
      - leantime_db                                                     # Don't start Leantime unles leantime_db is running

networks:
  lean_network:
